#!/bin/bash -u

if [ $USER == 'root' ]; then USER=$SUDO_USER; HOME="/home/${USER}"; fi
SCRIPT=`readlink -f $0`; SCRIPTPATH=`dirname "$SCRIPT"`; cd "$SCRIPTPATH";
PROCESS_TYPE=; if [ "$#" -eq 0 ]; then PROCESS_TYPE="--build"; else PROCESS_TYPE=${1}; fi
case ${PROCESS_TYPE} in
  "--deploy") ;&
  "--purge") ;&
  "--build")
    if [[ "$0" != "tools/package" && "$0" != "./tools/package" ]]; then
      echo "Must be run from parent project containing directory NOT $0";
      exit 1;
    fi
    if [[ $EUID -ne 0 ]]; then
       echo "This script must be run as root" 1>&2;
       exit 1;
    fi
    read -p "Save package as location/name_version-release_architecture.deb [../CD-ROM-auto-RIPper_0.1-0_all.deb]: " SAVE_AS;
    SAVE_AS=${SAVE_AS:-"../CD-ROM-auto-RIPper_0.1-0_all.deb"};
  case ${PROCESS_TYPE} in
    "--deploy") ;&
    "--purge") ;&
    "--build")
      echo "BUILDING..."
      if [ -f ${SAVE_AS} ]; then rm -f ${SAVE_AS}; fi
      sudo chown -R root:root ../debian/usr;
      sudo chmod -R +x ../debian/usr;
      sudo chown -R root:root ../debian/etc;
      sudo dpkg-deb --build ../debian;
      echo "renaming '../debian.deb' to '${SAVE_AS}'";
      mv ../debian.deb ${SAVE_AS};
      sudo chmod 775 ${SAVE_AS};
      sudo chown ${USER}:${USER} ${SAVE_AS};
      sudo chown -R ${USER}:${USER} ../debian;
      echo "BUILD SUCCESFULLY COMPLETED!";
      ;;
  esac
  case ${PROCESS_TYPE} in
    "--deploy") ;&
    "--purge")
      echo "PURGING...";
      sudo apt remove cd-rom-auto-ripper -y;
      sudo apt autoremove;
      echo "PURGE SUCCESFULLY COMPLETED!";
      ;;
  esac
  case ${PROCESS_TYPE} in
    "--deploy")
      echo "DEPLOYING..."
      sudo apt install udev ubuntu-restricted-extras ubuntu-restricted-addons handbrake-cli libva-dev libdrm-dev libdvd-pkg libdvdread-dev abcde flac -y;
      sudo dpkg -i ${SAVE_AS};
      if [ $? -ne 0 ]; then
        cd "$SCRIPTPATH";
        sudo apt -yf install
      fi
      echo "DEPLOY SUCCESFULLY COMPLETED!";
      ;;
  esac
    ;;
  *)
    echo "USAGE: ...";
    exit 1
    ;;
esac
exit 0;