#!/bin/bash -eu

if [[ "$0" != "tools/test" && "$0" != "./tools/test" ]]; then
  echo "Must be run from parent project containing directory NOT $0";
  exit 1;
fi

if [[ $EUID -ne 0 ]]; then
    echo "This script must be run as root" 1>&2;
    exit 1;
fi

if [ $USER == 'root' ]; then USER=$SUDO_USER; HOME="/home/${SUDO_USER}"; fi
while [[ "${HOME}" == "/root" || ! -d "${HOME}" ]]; do
  echo "USER HOME PATH ${HOME} IS INVALID!";
  read -p "Enter username: " USERNAME
  HOME=`echo "/home/${USERNAME}"`;
done
export HOME;

RESPONSE=;
log_response () {
  echo -e "$1\n";
  RESPONSE+="$1\n";
}

# CLEAN UP
GOOD=0;
purge () {
  echo "CLEANING UP...";
}
clean () {
  purge;
  if [[ ${GOOD} == 1 ]]; then
    echo -e "\nFULL REPORT";
    echo -e $RESPONSE;
  else 
    echo -e "\nTESTS \e[0;31mFAILED TO COMPLETE!\e[0m";
  fi
}
trap clean EXIT;
sudo apt upgrade -y;
purge;

tools/package --deploy;

GOOD=1;
exit 0;
